---
title: "30538 Pset 4"
author: "Brook Jaffe"
date: "7 February 2026"
format: 
  pdf:
    include-in-header: 
       text: |
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
include-before-body:
  text: |
    \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
      showspaces = false,
      showtabs = false,
      breaksymbolleft={},
      breaklines
    }
output:
  echo: false
  eval: false
---

**Due 02/07 at 5:00PM Central.**

"This submission is my work alone and complies with the 30538 integrity policy." Add your initials to indicate your agreement: BGJ

### Github Classroom Assignment Setup and Submission Instructions

1.  **Accepting and Setting up the PS4 Assignment Repository**
    -   Each student must individually accept the repository for the problem set from Github Classroom ("ps4") -- <https://classroom.github.com/a/hWhtcHqH>
        -   You will be prompted to select your cnetid from the list in order to link your Github account to your cnetid.
        -   If you can't find your cnetid in the link above, click "continue to next step" and accept the assignment, then add your name, cnetid, and Github account to this Google Sheet and we will manually link it: <https://rb.gy/9u7fb6>
    -   If you authenticated and linked your Github account to your device, you should be able to clone your PS4 assignment repository locally.
    -   Contents of PS4 assignment repository:
        -   `ps4_template.qmd`: this is the Quarto file with the template for the problem set. You will write your answers to the problem set here.
2.  **Submission Process**:
    -   Knit your completed solution `ps4.qmd` as a pdf `ps4.pdf`.
        -   Your submission does not need runnable code. Instead, you will tell us either what code you ran or what output you got.
    -   To submit, push `ps4.qmd` and `ps4.pdf` to your PS4 assignment repository. Confirm on Github.com that your work was successfully pushed.

### Grading
- You will be graded on what was last pushed to your PS4 assignment repository before the assignment deadline
- Problem sets will be graded for completion as: {missing (0%); ✓- (incomplete, 50%); ✓+ (excellent, 100%)}
    - The percent values assigned to each problem denote how long we estimate the problem will take as a share of total time spent on the problem set, not the points they are associated with.
- In order for your submission to be considered complete, you need to push both your `ps4.qmd` and `ps4.pdf` to your repository. Submissions that do not include both files will automatically receive 50% credit.


\newpage

```{python}
import pandas as pd
import altair as alt
import time

import warnings 
warnings.filterwarnings('ignore')
alt.renderers.enable("png")
```


## Step 1: Develop initial scraper and crawler


```{python}
import requests
with open(r'/Users/brookjaffe/Desktop/MPP/DAPII/ps4-bjaffe1/Enforcement Actions _ Office of Inspector General _ Government Oversight _ U.S. Department of Health and Human Services.html', 'r') as page:
  text = page.read()
from bs4 import BeautifulSoup
soup = BeautifulSoup(text, 'lxml')
date_html = soup.find_all('span', class_ = 'text-base-dark padding-right-105')
category_html = soup.find_all('li', class_ = 'display-inline-block usa-tag text-no-lowercase text-base-darkest bg-base-lightest margin-right-1')
title_html = soup.find_all('h2', class_ = 'usa-card__heading')

date_column = []
for date in date_html:
  date_only = date.text
  date_column.append(date_only)

cat_column = []
for category in category_html:
  cat = category.text
  cat_column.append(cat)

title_column = []
for title in title_html:
  title_text = title.text[1:-1]
  title_column.append(title_text)

updated_cats = []
for i in range(len(cat_column)):
  if cat_column[i] == 'COVID-19':
    new_cat = 'COVID-19, Criminal and Civil Actions'
  elif cat_column[i-1] == 'COVID-19':
    new_cat = None
  else:
    new_cat = cat_column[i]
  updated_cats.append(new_cat)
updated_cats = filter(None, updated_cats)
updated_cats = list(updated_cats)

link_column = []
for action in title_html:
  link = action.find('a').get('href')
  link_column.append(link)

scraped_df = pd.DataFrame({'title': title_column, 
                           'date': date_column,
                           'enforcement_category': updated_cats,
                           'link': link_column})

print(scraped_df.head())
```

## Step 2: Making the scraper dynamic

### 1. Turning the scraper into a function 

* a. Pseudo-Code
Step 1: Check if the year is >= 2013

  Step 1a: If yes, proceed to step 2

  Step 1b: If no, remind the user to input a date that is in 2013 or later

Step 2: Inspect page html

Step 3: Check if any enforcement actions on the page have a date preceding the month and year requested

  Step 3a: If yes, collect all enforcement actions above that one

  Step 3b: If no, collect all enforcement actions on the page and precede to step 4

Step 4: Parse html and extract the url to go to the next page

Step 5: Follow that link

Step 6: Repeat steps 3-5 until the month+year prior to the one requested is reached

Step 7: Compile the collected information into a dataframe

* b. Create Dynamic Scraper

```{python}
#| eval: true
#| echo: false

def get_enforcement(monthplusyear):
  datetime = pd.to_datetime(monthplusyear)
  if datetime.year < 2013:
    print('Cannot fetch enforcement actions prior to 2013. Please input a new date, making sure that it is January 2013 or later.')
  else:
    url = 'https://oig.hhs.gov/fraud/enforcement/'
    title_column = []
    date_column = []
    category_column = []
    link_column = []

    for i in range(535):
      time.sleep(1)
      response = requests.get(url)
      soup = BeautifulSoup(response.content, 'lxml')
    
      for item in soup.find_all('div', class_ = 'usa-card__container'):
        date = item.find('span', class_ = 'text-base-dark padding-right-105')
        t = pd.to_datetime(date.text)
        if t < datetime:
          #updated_cats = []
          '''for n in range(len(category_column)):
            if category_column[n] == 'COVID-19':
              new_cat = 'COVID-19, Criminal and Civil Actions'
            elif category_column[n-1] == 'COVID-19':
              new_cat = None
            else:
              new_cat = category_column[n]
            updated_cats.append(new_cat)
          updated_cats = filter(None, updated_cats)
          updated_cats = list(updated_cats)'''
          df_final = pd.DataFrame({'title': list(title_column), 
                                 'date': list(date_column),
                                 'enforcement_category': category_column,
                                 'link': list(link_column)})
          df_final.to_csv(f'enforcement_actions_{datetime.year}_{datetime.month}.csv')
          return None
        else:
          title_column.append(item.find('h2', class_ = 'usa-card__heading').text[1:-1])
          date_column.append(date.text)
          category_column.append(item.find('li', class_ = 'display-inline-block usa-tag text-no-lowercase text-base-darkest bg-base-lightest margin-right-1').text)
          link_column.append(item.find('a').get('href'))
      url = 'https://oig.hhs.gov/fraud/enforcement/?page='+str(i)
```

```{python}
#| eval: false
get_enforcement('January 2024')
```

```{python}
jan_2024 = pd.read_csv('/Users/brookjaffe/Desktop/MPP/DAPII/ps4-bjaffe1/enforcement_actions_2024_1.csv')
print(jan_2024.shape)
print(jan_2024.tail())
```

There are 1,811 enforcement actions in the final dataframe, with the earliest being the indictment of a former nurse aide from January 3, 2024 in the State Enforcement Agencies category.

* c. Test Your Code

```{python}
get_enforcement('January 2022')
```

## Step 3: Plot data based on scraped data

### 1. Plot the number of enforcement actions over time

```{python}

```

### 2. Plot the number of enforcement actions categorized:

* based on "Criminal and Civil Actions" vs. "State Enforcement Agencies"

```{python}
df_enforcement = pd.read_csv('/Users/brookjaffe/Desktop/MPP/DAPII/ps4-bjaffe1/enforcement_actions_2022_1.csv')
df_enforcement['date'] = pd.to_datetime(df_enforcement['date'])

enforcement_over_time = alt.Chart(df_enforcement).mark_area(
  color='lightblue',
  interpolate='step-after',
  line=True
).encode(
  x = alt.X().title('Time')
  y = alt.X
)
```

* based on five topics

```{python}

```
